<?php 

function goya_vc_templates_homepage($template_list) {
	$template_list['home_01'] = array(
		'name' => esc_html__( 'Decor 01 - Classic', 'goya-core' ),
		'thumbnail' => GOYA_THEME_URI."/assets/img/visual-composer/templates/homepages/home-h1.jpg",
		'cat' => array( 'homepage' ),
		'sc' => '[vc_row et_full_width="true" et_column_align="align-center" css=".vc_custom_1579117366191{margin-bottom: 60px !important;}"][vc_column offset="vc_col-lg-11"][et_banner_slider arrows="1" pagination="1" infinite="1" autoplay="1" pause="1" background_color="#f6f6f6"][et_banner image_type="css" height="70" link_type="text_link" link_style="link" link_color="accent" title_size="xlarge" text_animation="et-fadeInRight" text_position="h_left-v_center" title="A warm enlightenment" subtitle="Bobber Pendant Light" image_id="515" img_size="full" link="title:Buy%20Now||"][et_banner image_type="css" height="70" link_type="text_link" link_style="link" link_color="accent" title_size="xlarge" text_animation="et-fadeInUp" text_position="h_right-v_center" text_alignment="align_right" title="Wall clock renaissance" subtitle="All Brass Clock" image_id="520" img_size="full" link="title:Shop%20Now||"][et_banner image_type="css" height="70" text_color_scheme="light" link_type="text_link" link_style="link" title_size="xlarge" title_color="accent" text_animation="et-fadeInUp" text_position="h_left-v_center" title="A lamp with personality" image_id="1732" img_size="full" link="title:Shop%20Now||" subtitle="Light on your ears"][/et_banner_slider][/vc_column][/vc_row][vc_row css=".vc_custom_1579117484725{margin-bottom: 40px !important;}"][vc_column][vc_row_inner content_placement="middle"][vc_column_inner animation="animation bottom-to-top" offset="vc_col-lg-6" css=".vc_custom_1578689961180{margin-bottom: 30px !important;padding-top: 10% !important;padding-right: 40% !important;padding-bottom: 10% !important;padding-left: 10% !important;background: #f2f2f2 url(https://goyacdn.everthemes.com/demo-decor/wp-content/uploads/sites/2/2019/09/banner-halfsize-pendant.jpg?id=668) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;border-radius: 3px !important;}"][vc_column_text]
			<p class="fancy-title accent-color">Accessories</p>

			<h2 class="wpb_wrapper">Clearance Sales</h2>
			<p class="wpb_wrapper">Up to 70% Off &amp; Free Shipping</p>
			[/vc_column_text][et_button title="All discount sales" add_arrow="true" size="sm" style="outlined" link="title:Shop||"][/vc_column_inner][vc_column_inner animation="animation bottom-to-top" offset="vc_col-lg-6" css=".vc_custom_1578690023924{margin-bottom: 30px !important;padding-top: 10% !important;padding-right: 40% !important;padding-bottom: 10% !important;padding-left: 10% !important;background-image: url(https://goyacdn.everthemes.com/demo-decor/wp-content/uploads/sites/2/2019/09/banner-halfsize-clock-stone.jpg?id=667) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column_text]
			<p class="fancy-title accent-color">Clearance</p>

			<h2 class="wpb_wrapper">Free Shipping</h2>
			<p class="wpb_wrapper">Clean, clever and natural furniture.</p>
			[/vc_column_text][et_button title="All discount sales" add_arrow="true" size="sm" style="outlined" link="title:Shop||"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner animation="animation left-to-right" offset="vc_col-lg-6" css=".vc_custom_1578690040935{margin-bottom: 30px !important;padding-top: 10% !important;padding-right: 10% !important;padding-bottom: 10% !important;padding-left: 10% !important;background-color: #f2f2f2 !important;border-radius: 3px !important;}"][vc_column_text]
			<p class="fancy-title accent-color">Shop Women</p>

			<h2 class="wpb_wrapper">Huge Discounts</h2>
			<div class="wpb_text_column wpb_content_element ">
			<div class="wpb_wrapper">
			<p class="wpb_wrapper">Top designers to create contemporary furniture. Narwhal typewriter XOXO try-hard pitchfork irony.</p>

			</div>
			</div>
			[/vc_column_text][et_button title="All discount sales" add_arrow="true" size="sm" style="outlined" link="title:Shop||"][vc_empty_space][/vc_column_inner][vc_column_inner offset="vc_col-lg-6" css=".vc_custom_1569352232876{margin-bottom: 20px !important;}"][et_product_slider product_sort="latest-products" item_style="style2" columns="2"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_column_align="align-center" content_placement="middle"][vc_column animation="animation bottom-to-top" css=".vc_custom_1579143688636{padding-top: 60px !important;padding-right: 15% !important;padding-bottom: 40px !important;padding-left: 15% !important;background-color: #edead3 !important;}"][vc_row_inner et_column_align="align-center" content_placement="top"][vc_column_inner offset="vc_col-lg-8"][vc_column_text]
			<h5 class="fancy-title accent-color" style="text-align: center;">Connected Spaces</h5>
			<h2 style="text-align: center;">Redefine how we use space</h2>
			<p style="text-align: center;">Top designers and craftspeople around the world to create contemporary furniture, lighting and accessories that are clean, clever and natural.</p>
			[/vc_column_text][vc_empty_space height="20px"][/vc_column_inner][/vc_row_inner][vc_row_inner et_column_align="align-center" content_placement="top"][vc_column_inner][et_icon_holder columns_large="4" center="true"][et_iconbox icon_pixeden="pe-7s-shuffle" layout="centered" title="Free Shipping"]Pinterest succulents raclette everyday carry.[/et_iconbox][et_iconbox icon_pixeden="pe-7s-refresh" layout="centered" title="30 days return"]Irony vape green juice pop-up pork belly.[/et_iconbox][et_iconbox icon_pixeden="pe-7s-plane" layout="centered" title="International Warranty"]Williamsburg letterpress 90’s.[/et_iconbox][/et_icon_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" content_placement="middle" css=".vc_custom_1579117762105{padding-top: 60px !important;padding-bottom: 40px !important;}"][vc_column][vc_row_inner equal_height="yes" content_placement="middle"][vc_column_inner animation="animation bottom-to-top" offset="vc_col-lg-5" css=".vc_custom_1578690793958{margin-bottom: 30px !important;padding-top: 10% !important;padding-right: 10% !important;padding-bottom: 10% !important;padding-left: 10% !important;background-color: #f2f2f2 !important;}"][vc_column_text]
			<h5 class="fancy-title accent-color">Featured</h5>
			<h2>Portfolio</h2>
			Pop-up mixtape pinterest succulents raclette everyday carry. Microdosing glossier drinking vinegar.[/vc_column_text][vc_empty_space height="10px"][et_button title="All Looks" add_arrow="true" style="outlined" link="||"][/vc_column_inner][vc_column_inner animation="animation top-to-bottom" offset="vc_col-lg-7"][et_portfolio columns="2" item_style="overlay" num_posts="4"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1579117855735{padding-bottom: 40px !important;}"][vc_column animation="animation bottom-to-top"][vc_row_inner el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][vc_column_text]
			<h2>Editor Picks</h2>
			Irony vape green juice pop-up pork belly, kitsch shabby chic. Williamsburg letterpress 90s.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner][et_product_slider product_sort="latest-products" item_style="style4" carousel="no"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true"][vc_column][vc_separator css=".vc_custom_1556305572662{margin-bottom: 0px !important;}"][/vc_column][/vc_row][vc_row css=".vc_custom_1579117433533{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column animation="animation bottom-to-top"][vc_row_inner el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][vc_column_text]
			<h2>Latest News</h2>
			Knausgaard meditation gochujang 8-bit scenester franzen gastropub distillery biodiesel.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner][et_posts num_posts="4" style="carousel" post_excerpt="1"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);

	$template_list['home_02'] = array(
		'name' => esc_html__( 'Decor 02 - Product Landing', 'goya-core' ),
		'thumbnail' => GOYA_THEME_URI . "/assets/img/visual-composer/templates/homepages/home-h2.jpg",
		'cat' => array( 'homepage' ),
		'sc' => '[vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center"][vc_column][et_banner_slider arrows="1" pagination="1" infinite="1" autoplay="1" pause="1" background_color="#f6f6f6"][et_banner image_type="css" height="90" link_type="text_link" link_style="outlined" title_size="xxlarge" subtitle_type="tag_style" text_animation="et-fadeInUp" text_position="h_right-v_center" text_alignment="align_right" title="Sculptural Illumination" subtitle="Sophisticated Built" image_id="842" img_size="full" link="title:Shop%20Now||" paragraph="Pleasant, glare-free illumination delivered via sculptural fixtures."][et_banner image_type="css" height="90" link_type="text_link" link_style="outlined" title_size="xxlarge" subtitle_type="tag_style" text_animation="et-fadeInRight" text_position="h_right-v_center" text_alignment="align_right" title="Cast Aluminum Forms" subtitle="Industrial Design" image_id="843" img_size="full" link="title:Buy%20Now||" paragraph="Geometric forms rendered in industrial, cast aluminum."][et_banner image_type="css" height="90" link_type="text_link" link_style="outlined" title_size="xxlarge" subtitle_type="tag_style" text_animation="et-fadeInUp" text_position="h_right-v_center" text_alignment="align_right" title="Smooth Finish Aluminum" subtitle="Superb Finish" image_id="844" img_size="full" link="title:Shop%20Now||" paragraph="Cast aluminum with a smooth, warm and tactile finish."][/et_banner_slider][/vc_column][/vc_row][vc_row css=".vc_custom_1580617901389{padding-top: 60px !important;padding-bottom: 40px !important;}"][vc_column][vc_row_inner content_placement="middle"][vc_column_inner width="2/3"][et_image image="780"][/et_image][/vc_column_inner][vc_column_inner width="1/3"][et_iconbox icon_pixeden="pe-7s-light" layout="icon_left" icon_style="background" title="Industrial Design"]Geometric forms rendered in industrial, cast aluminum.[/et_iconbox][vc_empty_space][et_iconbox icon_pixeden="pe-7s-upload" layout="icon_left" icon_style="background" title="Sophisticated Built"]Pleasant, glare-free illumination delivered via sculptural fixtures.[/et_iconbox][vc_empty_space][et_iconbox icon_pixeden="pe-7s-paint" layout="icon_left" icon_style="background" title="Superb Finish"]Cast aluminum with a smooth, warm and tactile finish.[/et_iconbox][/vc_column_inner][/vc_row_inner][vc_row_inner et_column_align="align-center" css=".vc_custom_1580617950088{padding-top: 60px !important;}"][vc_column_inner width="1/3" animation="animation bottom-to-top"][vc_column_text]
			<h5 class="fancy-title accent-color">Outstanding Design</h5>
			<h2>The Cast Lighting Series’ aesthetic presence rivals its versatility.</h2>
			[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][/vc_column_inner][/vc_row_inner][vc_row_inner et_column_align="align-center"][vc_column_inner width="1/3" animation="animation bottom-to-top"][vc_column_text]Such is the nature of the Cast Lighting Series. Designers Tom Chung and Jordan Murphy based the first designs – the Cast Pendants – on age-old plumb weights that masons and carpenters have been hanging from lines since ancient Egyptian times to establish a true vertical.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/3" animation="animation bottom-to-top"][vc_column_text]The series also channels philosophy of soft minimalism, offsetting strict, geometric forms rendered in industrial, cast aluminum with a smooth, warm and tactile finish.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center" content_placement="middle" parallax="content-moving" parallax_speed_bg="1.8" css=".vc_custom_1578698867596{padding-top: 120px !important;padding-bottom: 120px !important;background: #353535 url(https://goyacdn.everthemes.com/demo-decor/wp-content/uploads/sites/2/2019/09/banner-harbour-chair.jpg?id=695);}"][vc_column et_column_color="et-light-column"][vc_row_inner et_column_align="align-center" content_placement="top" el_class="align-center"][vc_column_inner el_class="text-center" animation="animation bottom-to-top"][vc_column_text]
			<h5 class="fancy-title accent-color">Connected Spaces</h5>
			<h2>Redefine how we use space</h2>
			Top designers and craftspeople around the world to create contemporary furniture, lighting and accessories that are clean, clever and natural.[/vc_column_text][vc_empty_space height="20px"][/vc_column_inner][/vc_row_inner][vc_row_inner et_column_align="align-center" content_placement="top" el_class="align-center"][vc_column_inner el_class="text-center" animation="animation bottom-to-top"][et_icon_holder columns_large="4" center="true"][et_iconbox icon_pixeden="pe-7s-refresh" layout="centered" title="30 days return"]Irony vape green juice pop-up pork belly.[/et_iconbox][/et_icon_holder][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" css=".vc_custom_1579120979162{padding-top: 60px !important;padding-bottom: 40px !important;background-color: #f2f2f2 !important;}"][vc_column animation="animation bottom-to-top"][vc_row_inner el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][vc_column_text]
			<h2>Editor Picks</h2>
			Irony vape green juice pop-up pork belly, kitsch shabby chic. Williamsburg letterpress 90s.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner][et_product_slider product_sort="latest-products" item_style="style4" carousel="no"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center" content_placement="middle" css=".vc_custom_1578698874749{padding-top: 120px !important;padding-bottom: 120px !important;background: #595959 url(https://goyacdn.everthemes.com/demo-decor/wp-content/uploads/sites/2/2019/09/banner_knitted_chair.jpg?id=675) !important;}"][vc_column et_column_color="et-light-column"][vc_row_inner et_column_align="align-center" content_placement="top" el_class="align-center"][vc_column_inner el_class="text-center" animation="animation bottom-to-top" offset="vc_col-lg-8"][vc_column_text]
			<h5 class="fancy-title accent-color">Connected Spaces</h5>
			<h2>Redefine how we use space</h2>
			Top designers and craftspeople around the world to create contemporary furniture, lighting and accessories that are clean, clever and natural.[/vc_column_text][vc_empty_space height="20px"][et_video_lightbox icon_color="#ffffff" video="https://www.youtube.com/watch?v=1KahlicghaE"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1579121000707{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column animation="animation bottom-to-top"][vc_row_inner][vc_column_inner][vc_column_text]
			<h5 class="fancy-title accent-color" style="text-align: center;">Outstanding</h5>
			<h2 style="text-align: center;">Designers Portfolio</h2>
			<p style="text-align: center;">The Cast Lighting Series’ aesthetic presence rivals its versatility.</p>
			[/vc_column_text][et_portfolio num_posts="4"][et_button title="View All" shadow="button-shadow" align="center" link="title:View%20All||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	
	$template_list['home_03'] = array(
		'name' => esc_html__( 'Decor 03 - Full Screen', 'goya-core' ),
		'thumbnail' => GOYA_THEME_URI . "/assets/img/visual-composer/templates/homepages/home-h3.jpg",
		'cat' => array( 'homepage' ),
		'sc' => '[vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center" full_height="yes" disable_element="yes" css=".vc_custom_1580666584603{margin-bottom: 30px !important;}"][vc_column et_column_color="et-light-column"][et_banner_slider arrows="1" pagination="1" pagination_color="light" infinite="1" autoplay="5000" background_color="#f6f6f6"][et_banner image_type="css" height="100" text_color_scheme="light" link_type="text_link" link_style="link" title_size="xlarge" text_animation="et-fadeInRight" text_position="h_left-v_center" title="New Arrivals" subtitle="Summer 19" image_id="675" img_size="full" text_padding="10" text_width="50" link="title:Explore%20Now||"][et_banner image_type="css" height="100" text_color_scheme="light" link_type="text_link" link_style="link" title_size="xlarge" text_animation="et-fadeInUp" text_alignment="align_center" title="Beach Collection" subtitle="Fresh Colors" image_id="695" img_size="full" text_padding="10" link="title:Shop%20Now||" text_width="50"][et_banner image_type="css" height="100" text_color_scheme="light" link_type="text_link" link_style="outlined" title_size="xlarge" text_animation="et-fadeInUp" text_position="h_left-v_center" title="Light Shades" subtitle="Summer Looks" image_id="678" img_size="full" text_padding="10" link="title:Shop%20Now||" text_width="50"][/et_banner_slider][/vc_column][/vc_row][vc_row et_full_width="true" css=".vc_custom_1573099524074{background-color: #aaa097 !important;}"][vc_column][vc_row_inner][vc_column_inner][rev_slider alias="home-3"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1579121223603{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column][vc_row_inner][vc_column_inner][vc_column_text css=".vc_custom_1579022815067{margin-bottom: 30px !important;}"]
			<div style="text-align: center;">
			<h5 class="fancy-tag accent-color">Featured</h5>
			</div>
			<h2 style="text-align: center;"><strong>Featured Products</strong></h2>
			[/vc_column_text][et_product_slider product_sort="latest-products" item_count="8" show_variations="true"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" css=".vc_custom_1579121231952{padding-top: 60px !important;padding-bottom: 60px !important;background-color: #f2f2f2 !important;}"][vc_column][vc_row_inner][vc_column_inner][vc_column_text css=".vc_custom_1579022840120{margin-bottom: 30px !important;}"]
			<div style="text-align: center;">
			<h5 class="fancy-tag accent-color">New Designs</h5>
			</div>
			<h2 style="text-align: center;"><strong>Light up the Darkness</strong></h2>
			<p style="text-align: center;">Our most popular lighting designs are created with your needs in mind.</p>
			[/vc_column_text][vc_empty_space][et_product_slider product_sort="latest-products" item_count="8" show_variations="true"][vc_empty_space][et_button title="View All" animation="animation bottom-to-top" color="#ffffff" align="center" link="title:View%20All||" text_color="#000000"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_column_align="align-center" content_placement="middle" css=".vc_custom_1579121240589{padding-top: 60px !important;padding-bottom: 60px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: contain !important;}"][vc_column et_column_overlap="overlap-right" width="1/3" animation="animation left-to-right"][vc_column_text]
			<div style="text-align: right;">
			<h5 class="fancy-tag accent-color">Concept</h5>
			</div>
			<h1 style="text-align: right;">Blissfully simple design</h1>
			<p style="text-align: right;">Like the original, the chair is deconstructed and stripped of unnecessary components.</p>
			[/vc_column_text][/vc_column][vc_column width="1/3" animation="animation bottom-to-top"][et_image image="423" img_size="large"][/et_image][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true"][vc_column][vc_separator][/vc_column][/vc_row][vc_row css=".vc_custom_1579121248274{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column width="1/3"][et_iconbox icon_pixeden="pe-7s-refresh" layout="centered" title="30 Days Returns" link="|||"]Salvia truffaut vice man braid hashtag helvetica mustache.[/et_iconbox][/vc_column][vc_column width="1/3"][et_iconbox icon_pixeden="pe-7s-paper-plane" layout="centered" title="Free Shipping"]Mustache XOXO green juice irony, activated charcoal affogato whatever.[/et_iconbox][/vc_column][vc_column width="1/3"][et_iconbox icon_pixeden="pe-7s-lock" layout="centered" title="International Warranty"]Mustache XOXO green juice irony, activated charcoal affogato whatever[/et_iconbox][/vc_column][/vc_row][vc_row css=".vc_custom_1579121261219{padding-bottom: 60px !important;}"][vc_column][et_posts num_posts="6" style="carousel" post_excerpt="1"][/vc_column][/vc_row]',
	);
	
	$template_list['home_04'] = array(
		'name' => esc_html__( 'Decor 04 - Minimal', 'goya-core' ),
		'thumbnail' => GOYA_THEME_URI . "/assets/img/visual-composer/templates/homepages/home-h4.jpg",
		'cat' => array( 'homepage' ),
		'sc' => '[vc_row et_full_width="true" et_row_padding="true" full_height="yes" css=".vc_custom_1579121372592{padding-top: 120px !important;padding-bottom: 60px !important;background-color: #f2f2f2 !important;}"][vc_column][vc_row_inner][vc_column_inner][vc_column_text animation="animation bottom-to-top" css=".vc_custom_1578771779192{margin-bottom: 30px !important;}"]
			<h2 style="text-align: center;">Lightning Collection</h2>
			[/vc_column_text][vc_empty_space][et_product_slider product_sort="latest-products" item_count="8" item_style="style2"][vc_empty_space height="60px"][et_button title="Browse all models" add_arrow="true" animation="animation bottom-to-top" style="outlined" align="center" link="title:Shop||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1579121455994{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column et_column_color="et-light-column" animation="animation scale" css=".vc_custom_1579023389092{padding-top: 70px !important;padding-right: 50px !important;padding-bottom: 70px !important;padding-left: 50px !important;background-color: #000000 !important;}"][vc_column_text css=".vc_custom_1578771309064{margin-bottom: 0px !important;}"]
			<h2 style="text-align: center;"><strong>Light Up the Darkness</strong></h2>
			<p style="text-align: center;"><a href="#">Table Lamps</a>        <a href="#">Pendant Lights</a>        <a href="#">Accessories</a></p>
			[/vc_column_text][/vc_column][/vc_row][vc_row css=".vc_custom_1579121384850{padding-bottom: 60px !important;}"][vc_column][vc_row_inner][vc_column_inner][vc_column_text animation="animation bottom-to-top" css=".vc_custom_1569361878501{margin-bottom: 30px !important;}"]
			<h2 style="text-align: center;">Best Sellers</h2>
			<p style="text-align: center;">Outfit ideas, editor picks, styling inspiration and Face + Body tips</p>
			[/vc_column_text][et_product_slider product_sort="latest-products"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row][vc_column][vc_separator][/vc_column][/vc_row][vc_row et_column_align="align-center" css=".vc_custom_1579121392803{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column][vc_row_inner][vc_column_inner][vc_column_text animation="animation bottom-to-top" css=".vc_custom_1582004013980{margin-bottom: 30px !important;}"]
			<h2 style="text-align: center;">Blog</h2>
			<p style="text-align: center;">Outfit ideas, editor picks, styling</p>
			[/vc_column_text][et_posts num_posts="4" style="carousel" columns="4"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);

	$template_list['home_05'] = array(
		'name' => esc_html__( 'Decor 05 - Dark', 'goya-core' ),
		'thumbnail' => GOYA_THEME_URI . "/assets/img/visual-composer/templates/homepages/home-h10.jpg",
		'cat' => array( 'homepage' ),
		'sc' => '[vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center"][vc_column][et_banner image_type="css" height="100" text_color_scheme="light" link_type="text_link" link_style="outlined" title_size="xlarge" text_animation="et-fadeInUp" text_alignment="align_center" title="Flip the switch, change your sound" subtitle="Iconic Retro Design" image_id="1614" img_size="full" link="title:Shop%20Now||"][/vc_column][/vc_row][vc_row et_full_width="true" css=".vc_custom_1579045790824{padding-top: 120px !important;padding-bottom: 120px !important;background-color: #f2f2f2 !important;}"][vc_column][vc_row_inner][vc_column_inner offset="vc_col-lg-7 vc_col-md-8"][vc_column_text]
			<h5 class="fancy-title accent-color">Kale Chips</h5>
			<h1>Disrupt single-origin coffee <span class="accent-color">quinoa cronut</span> jean shorts brooklyn.</h1>
			[/vc_column_text][vc_empty_space height="20px"][et_button title="Read More" add_arrow="true" style="outlined" align="center" link="title:Read%20More||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1579121637785{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column animation="animation bottom-to-top"][vc_row_inner el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][vc_column_text]
			<h2>Editor Picks</h2>
			Irony vape green juice pop-up pork belly, kitsch shabby chic. Williamsburg letterpress 90s.[/vc_column_text][vc_empty_space height="30px"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner][et_product_slider product_sort="latest-products" item_style="style4" carousel="no"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true"][vc_column][vc_separator css=".vc_custom_1556305572662{margin-bottom: 0px !important;}"][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center" css=".vc_custom_1579121645929{padding-top: 60px !important;padding-bottom: 60px !important;background-color: #282828 !important;}"][vc_column][vc_row_inner et_column_align="align-center"][vc_column_inner et_column_color="et-light-column" offset="vc_col-lg-8"][vc_column_text]
			<h2 style="text-align: center;">Portfolio</h2>
			<p style="text-align: center;">Microdosing glossier drinking vinegar.</p>
			[/vc_column_text][et_portfolio num_posts="4"][et_button title="View More" add_arrow="true" style="outlined" color="light" align="center" link="title:Portfolio||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true"][vc_column][vc_separator css=".vc_custom_1556305572662{margin-bottom: 0px !important;}"][/vc_column][/vc_row][vc_row css=".vc_custom_1579121652216{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column animation="animation bottom-to-top"][vc_row_inner el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][vc_column_text]
						<h2>Latest News</h2>
						Knausgaard meditation gochujang 8-bit scenester franzen gastropub distillery biodiesel.[/vc_column_text][vc_empty_space height="30px"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner][et_posts num_posts="4" style="carousel" post_excerpt="1"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" css=".vc_custom_1579045782594{padding-top: 120px !important;padding-bottom: 120px !important;background: #8c5c1d url(https://goyacdn.everthemes.com/demo-fashion/wp-content/uploads/sites/3/2019/05/black_dress.jpg?id=1983) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="showreel-row"][vc_column et_column_color="et-light-column"][vc_row_inner][vc_column_inner offset="vc_col-lg-6 vc_col-md-9"][vc_column_text animation="animation bottom-to-top"]
						<h2>Post-ironic venmo vegan ramps jean shorts disrupt asymmetrical.</h2>
						Banh mi schlitz cronut +1 swag. Gluten-free chicharrones portland thundercats health goth post-ironic.[/vc_column_text][et_video_lightbox style="lightbox-text" icon_size="small" video="https://www.youtube.com/watch?v=1KahlicghaE" video_text="View Trailer"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	
	$template_list['home_06'] = array(
		'name' => esc_html__( 'Fashion 01 - Classic', 'goya-core' ),
		'thumbnail' => GOYA_THEME_URI . "/assets/img/visual-composer/templates/homepages/home-h5.jpg",
		'cat' => array( 'homepage' ),
		'sc' => '[vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center"][vc_column][et_banner_slider arrows="1" pagination="1" infinite="1" animation="fade" autoplay="1" pause="1" background_color="#f6f6f6"][et_banner image_type="css" height="100" hover_effect="hover-zoom" link_type="text_link" link_style="link" title_size="xxlarge" subtitle_type="tag_style" text_animation="et-fadeInUp" text_position="h_left-v_center" title="New Cocktail Dresses" subtitle="50% OFF" image_id="4004" img_size="full" link="title:Shop%20Now||"][et_banner image_type="css" height="100" hover_effect="hover-zoom" link_type="text_link" link_style="link" title_size="xxlarge" subtitle_type="tag_style" text_animation="et-fadeInUp" text_position="h_right-v_center" text_alignment="align_right" title="Night Summer Dresses" subtitle="Summer 19" image_id="4002" img_size="full" link="title:Shop%20Now||"][et_banner image_type="css" height="100" hover_effect="hover-zoom" link_type="text_link" link_style="link" title_size="xxlarge" subtitle_type="tag_style" text_animation="et-fadeInRight" text_position="h_left-v_center" title="The Weekent Getaway" subtitle="Spring/Summer 19" image_id="4003" img_size="full" link="title:Browse%20styles||"][/et_banner_slider][/vc_column][/vc_row][vc_row css=".vc_custom_1579142078604{margin-top: 35px !important;margin-bottom: 35px !important;}"][vc_column][vc_row_inner equal_height="yes" content_placement="middle"][vc_column_inner animation="animation bottom-to-top" offset="vc_col-md-4" css=".vc_custom_1579111806249{margin-top: 15px !important;margin-bottom: 15px !important;}"][et_banner hover_effect="hover-zoom" link_type="text_link" link_style="solid" link_color="light" title_color="light" text_alignment="align_center" image_id="3814" title="Button Up Shirts" link="title:Buy%20Now||"][/vc_column_inner][vc_column_inner animation="animation bottom-to-top" offset="vc_col-md-4" css=".vc_custom_1579111815424{margin-top: 15px !important;margin-bottom: 15px !important;}"][et_banner hover_effect="hover-zoom" link_type="text_link" link_style="solid" link_color="light" title_color="light" text_alignment="align_center" image_id="3813" title="Choose your price" link="title:Choose%20Yours||"][/vc_column_inner][vc_column_inner et_column_color="et-light-column" animation="animation bottom-to-top" offset="vc_col-md-4" css=".vc_custom_1579129543433{margin-top: 15px !important;margin-bottom: 15px !important;padding-top: 60px !important;padding-right: 10% !important;padding-bottom: 60px !important;padding-left: 10% !important;background-color: #c7ab62 !important;}"][vc_column_text]
			<h2 class="wpb_wrapper" style="text-align: center;">Clearance Sales</h2>
			<p class="wpb_wrapper" style="text-align: center;">Up to 70% Off &amp; Free Shipping</p>
			[/vc_column_text][vc_empty_space height="20px"][et_button title="Browse sales" color="light" align="center" link="title:Shop||" text_color="#000000"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true"][vc_column][vc_separator css=".vc_custom_1556305572662{margin-bottom: 0px !important;}"][/vc_column][/vc_row][vc_row css=".vc_custom_1579142113600{margin-top: 60px !important;margin-bottom: 40px !important;}"][vc_column animation="animation bottom-to-top"][vc_row_inner el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][vc_column_text]
			<h2>Best Selling</h2>
			Bushwick blue bottle photo booth copper mug marfa craft beer pour-over swag subway tile organic cloud bread.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner][et_product_slider product_sort="latest-products" item_count="3" item_style="style3" carousel="no" columns="3"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" css=".vc_custom_1579111637642{padding-top: 60px !important;padding-bottom: 60px !important;background-color: #f1e8df !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-8 vc_col-md-9"][vc_column_text]
			<h2 style="text-align: center;">Testimonials</h2>
			[/vc_column_text][et_testimonial_slider arrows="true" pagination="true" autoplay="true" autoplay_speed="3000"][et_testimonial quote="Disrupt single-origin coffee hammock quinoa cronut jean shorts coloring book brooklyn seitan authentic craft beer." author_name="Sarah Connor" author_title="Waitress" author_image="3801"][et_testimonial quote="Pok pok flannel drinking vinegar, succulents lumbersexual XOXO artisan. Succulents tousled drinking vinegar, cardigan." author_name="Calvin Reeves" author_title="Actor" author_image="3762"][/et_testimonial_slider][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1579142142505{margin-top: 60px !important;margin-bottom: 35px !important;}"][vc_column animation="animation bottom-to-top"][vc_row_inner el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][vc_column_text]
			<h2>Trending Outfits</h2>
			Intelligentsia migas next level 90s woke ramps. Glossier vape celiac tumeric keffiyeh.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner][et_product_slider product_sort="by-category" cat="women" item_style="style2" carousel="no"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true"][vc_column][vc_separator css=".vc_custom_1556305572662{margin-bottom: 0px !important;}"][/vc_column][/vc_row][vc_row css=".vc_custom_1579111652347{margin-top: 60px !important;margin-bottom: 60px !important;}"][vc_column][vc_row_inner et_column_align="align-center" el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][vc_column_text]
			<h2 style="text-align: center;">Visit Us</h2>
			<p style="text-align: center;">Stop by our stores to learn the stories behind our products, get a personal styling session, or shop the latest in person. See our <a href="#">store locations</a>.</p>
			[/vc_column_text][/vc_column_inner][/vc_row_inner][et_image animation="animation scale" alignment="aligncenter" image="3545"][/et_image][/vc_column][/vc_row]',
	);
	
	$template_list['home_07'] = array(
		'name' => esc_html__( 'Fashion 02 - Full Screen', 'goya-core' ),
		'thumbnail' => GOYA_THEME_URI . "/assets/img/visual-composer/templates/homepages/home-h6.jpg",
		'cat' => array( 'homepage' ),
		'sc' => '[vc_row et_full_width="true" et_row_padding="true"][vc_column][et_banner_slider arrows="1" pagination="1" infinite="1" autoplay="1" pause="1" slider_type="full" background_color="#353535"][et_banner image_type="css" height="100" text_color_scheme="light" hover_effect="hover-zoom" title_size="xxlarge" text_animation="et-fadeInDown" text_position="h_left-v_center" title="New Arrivals" subtitle="Summer 19 Collection" image_id="1978" link="title:Shop||"][et_banner image_type="css" height="100" text_color_scheme="light" hover_effect="hover-zoom" title_size="xxlarge" text_animation="et-fadeInLeft" text_position="h_right-v_bottom" text_alignment="align_right" image_id="1976" title="Nightlife Collection" subtitle="Update your look" link="title:Shop||"][et_banner image_type="css" height="100" text_color_scheme="light" hover_effect="hover-zoom" title_size="xxlarge" text_animation="et-fadeInLeft" text_position="h_left-v_bottom" image_id="1980" title="Light Shades" subtitle="Fresh looks for summer" link="title:Shop||"][/et_banner_slider][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" disable_element="yes"][vc_column][rev_slider alias="home-6"][/vc_column][/vc_row][vc_row css=".vc_custom_1579114134724{padding-top: 60px !important;}"][vc_column][vc_row_inner content_placement="middle"][vc_column_inner animation="animation left-to-right" offset="vc_col-lg-6" css=".vc_custom_1578529138637{margin-bottom: 20px !important;padding-top: 10% !important;padding-right: 40% !important;padding-bottom: 10% !important;padding-left: 10% !important;background: #f2f2f2 url(https://goyacdn.everthemes.com/demo-fashion/wp-content/uploads/sites/3/2019/05/thinking_woman.jpg?id=1992) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column_text]
			<h6 class="fancy-tag light-color">SHOP WOMEN</h6>
			<h2 class="wpb_wrapper">Clearance Sales</h2>
			[/vc_column_text][vc_empty_space][et_button title="View Discounts" add_arrow="true" animation="animation bottom-to-top" style="link" color="dark" link="title:Shop||"][/vc_column_inner][vc_column_inner et_column_color="et-light-column" animation="animation right-to-left" offset="vc_col-lg-6" css=".vc_custom_1578529146980{margin-bottom: 20px !important;padding-top: 10% !important;padding-right: 10% !important;padding-bottom: 10% !important;padding-left: 40% !important;background-image: url(https://goyacdn.everthemes.com/demo-fashion/wp-content/uploads/sites/3/2019/04/smile.jpg?id=966) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column_text]
			<div style="text-align: right;">
			<h6 class="fancy-tag light-color">SHOP CASUAL</h6>
			</div>
			<h2 class="wpb_wrapper" style="text-align: right;">Free Shipping</h2>
			[/vc_column_text][vc_empty_space][et_button title="Buy Now" add_arrow="true" animation="animation bottom-to-top" style="link" color="light" align="right" link="title:Shop||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1579114145451{padding-bottom: 60px !important;}"][vc_column][vc_row_inner equal_height="yes" content_placement="middle"][vc_column_inner et_column_color="et-light-column" animation="animation left-to-right" offset="vc_col-lg-4" css=".vc_custom_1579726722992{margin-top: 15px !important;margin-bottom: 15px !important;padding-top: 10% !important;padding-right: 10% !important;padding-bottom: 10% !important;padding-left: 10% !important;background-color: #c7ab62 !important;}"][vc_column_text]
			<div style="text-align: center;">
			<h5 class="fancy-tag light-color">SHOP WOMEN</h5>
			</div>
			<h2 class="wpb_wrapper" style="text-align: center;">Clearance Sales</h2>
			[/vc_column_text][/vc_column_inner][vc_column_inner offset="vc_col-lg-8" css=".vc_custom_1578504088251{margin-top: 15px !important;margin-bottom: 15px !important;}"][et_product_slider product_sort="latest-products" item_count="6" item_style="style4" columns="3"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" css=".vc_custom_1579113105083{padding-top: 60px !important;padding-bottom: 40px !important;background-color: #f2f2f2 !important;}"][vc_column][vc_row_inner el_class="align-center"][vc_column_inner offset="vc_col-lg-6 vc_col-md-9"][vc_column_text]
			<h2 style="text-align: center;">LookBook</h2>
			<p style="text-align: center;">Pop-up mixtape pinterest succulents raclette everyday carry. Microdosing glossier drinking vinegar.</p>
			[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner content_placement="middle"][vc_column_inner][et_portfolio item_style="hover-card" num_posts="4"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1579114176683{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column][vc_row_inner el_class="align-center"][vc_column_inner offset="vc_col-lg-6 vc_col-md-9"][vc_column_text]
			<h2 style="text-align: center;">Trending Outfits</h2>
			<p style="text-align: center;">Intelligentsia 90s woke</p>
			[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner][et_product_slider product_sort="latest-products" item_count="6" show_variations="true"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row][vc_column][vc_separator][/vc_column][/vc_row][vc_row css=".vc_custom_1579114196093{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column][vc_row_inner el_class="align-center"][vc_column_inner offset="vc_col-lg-6 vc_col-md-9"][vc_column_text]
			<h2 style="text-align: center;">Latest News</h2>
			<p style="text-align: center;">Knausgaard meditation gochujang 8-bit scenester franzen gastropub distillery biodiesel.</p>
			[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner][et_posts num_posts="6" style="carousel"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	
	$template_list['home_08'] = array(
		'name' => esc_html__( 'Fashion 03 - New Season', 'goya-core' ),
		'thumbnail' => GOYA_THEME_URI . "/assets/img/visual-composer/templates/homepages/home-h7.jpg",
		'cat' => array( 'homepage' ),
		'sc' => '[vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center" full_height="yes" equal_height="yes" content_placement="middle" css=".vc_custom_1580269861254{background: #dae2d3 url(https://goyacdn.everthemes.com/demo-fashion/wp-content/uploads/sites/3/2019/04/beach.jpg?id=987) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column et_column_color="et-light-column"][vc_row_inner][vc_column_inner][et_typeauto typed_text="#E-8_JTNDZGl2JTIwc3R5bGUlM0QlMjJ0ZXh0LWFsaWduJTNBY2VudGVyJTIyJTNFJTJBU3VtbWVyJTIwU2FsZSUzQk5ldyUyMFNlYXNvbiUyQSUzQyUyRmRpdiUzRQ==" text_size="xxlarge" text_color="light"][vc_column_text animation="animation bottom-to-top"]
			<h4 style="text-align: center;">15% OFF + Free Shipping</h4>
			[/vc_column_text][et_button title="Shop Accessories" add_arrow="true" animation="animation left-to-right" color="light" align="center" link="||" text_color="#000000"][vc_empty_space][et_button title="Shop Swimsuits" add_arrow="true" animation="animation right-to-left" color="light" align="center" link="||" text_color="#000000"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1579113996430{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column][vc_row_inner][vc_column_inner][vc_column_text]
			<div class="wpb_text_column wpb_content_element ">
			<div class="wpb_wrapper">
			<h2 style="text-align: center;">Top Categories</h2>
			<p style="text-align: center;">Intelligentsia migas next level 90’s woke ramps. Glossier vape celiac tumeric keffiyeh.</p>

			</div>
			</div>
			[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner et_max_width=""][vc_column_inner width="1/4" animation="animation top-to-bottom"][et_image alignment="aligncenter" image="3814" img_size="large" img_link="||"][/et_image][vc_empty_space height="20px"][vc_column_text el_class="preline" css=".vc_custom_1579113319559{margin-bottom: 0px !important;}"]
			<h4>Swimwear</h4>
			[/vc_column_text][/vc_column_inner][vc_column_inner width="1/4" animation="animation bottom-to-top" css=".vc_custom_1579723187225{margin-top: 60px !important;}"][et_image alignment="aligncenter" image="3813" img_size="large" img_link="||"][/et_image][vc_empty_space height="20px"][vc_column_text el_class="preline" css=".vc_custom_1579113326365{margin-bottom: 0px !important;}"]
			<h4>Shirts &amp; Tops</h4>
			[/vc_column_text][/vc_column_inner][vc_column_inner width="1/4" animation="animation top-to-bottom"][et_image alignment="aligncenter" image="3815" img_size="large" img_link="||"][/et_image][vc_empty_space height="20px"][vc_column_text el_class="preline" css=".vc_custom_1579113332280{margin-bottom: 0px !important;}"]
			<h4>Blazers</h4>
			[/vc_column_text][/vc_column_inner][vc_column_inner width="1/4" animation="animation bottom-to-top" css=".vc_custom_1579723212503{margin-top: 60px !important;}"][et_image alignment="aligncenter" image="3812" img_size="large" img_link="||"][/et_image][vc_empty_space height="20px"][vc_column_text el_class="preline" css=".vc_custom_1579113338207{margin-bottom: 0px !important;}"]
			<h4>Accessories</h4>
			[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row content_placement="middle" css=".vc_custom_1579113269251{margin-bottom: 60px !important;}"][vc_column css=".vc_custom_1579721857677{background-color: #d2726b !important;}"][vc_row_inner content_placement="middle" el_class="align-center" css=".vc_custom_1557260034091{padding-top: 40px !important;padding-bottom: 40px !important;}"][vc_column_inner et_column_color="et-light-column" offset="vc_col-lg-3"][vc_column_text]
			<h4 style="text-align: center;"><span style="color: #ffffff;"><a style="color: #ffffff;" href="#">Women</a></span></h4>
			<h4 style="text-align: center;"><span style="color: #ffffff;"><a style="color: #ffffff;" href="#">Men</a></span></h4>
			<h4 style="text-align: center;"><span style="color: #ffffff;"><a style="color: #ffffff;" href="#">Accessories</a></span></h4>
			[/vc_column_text][/vc_column_inner][vc_column_inner et_column_color="et-light-column" el_class="text-center" offset="vc_col-lg-6"][vc_column_text]
			<h2 style="font-size: 60px; text-align: center;">50% OFF</h2>
			<h4 style="text-align: center;">Hundreds of styles</h4>
			[/vc_column_text][/vc_column_inner][vc_column_inner offset="vc_col-lg-3"][et_button title="Shop Now" add_arrow="true" size="lg" animation="animation bottom-to-top" color="light" shadow="button-shadow" align="center" text_color="#e01f1f"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center" css=".vc_custom_1579723272052{padding-top: 60px !important;padding-bottom: 60px !important;background-color: #fbe7d7 !important;}"][vc_column][vc_row_inner content_placement="middle"][vc_column_inner animation="animation scale"][vc_column_text]
			<h1 style="text-align: center;">80s Festival</h1>
			<p style="text-align: center;">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
			[/vc_column_text][et_product_slider product_sort="latest-products" item_count="8" show_variations="true"][vc_empty_space height="20px"][et_button title="View More" add_arrow="true" size="lg" animation="animation bottom-to-top" color="#ffffff" align="center" link="title:View%20More||" text_color="#44bf9e"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1579114009371{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column][vc_column_text]
			<h2 style="text-align: center;">Latest News</h2>
			<p style="text-align: center;">Knausgaard meditation gochujang 8-bit scenester franzen gastropub distillery biodiesel.</p>
			[/vc_column_text][et_posts style="carousel" columns="4"][/vc_column][/vc_row]',
	);
	
	$template_list['home_09'] = array(
		'name' => esc_html__( 'Fashion 04 - Product Landing', 'goya-core' ),
		'thumbnail' => GOYA_THEME_URI . "/assets/img/visual-composer/templates/homepages/home-h8.jpg",
		'cat' => array( 'homepage' ),
		'sc' => '[vc_row et_full_width="true" et_row_padding="true" css=".vc_custom_1579113527778{padding-top: 120px !important;padding-bottom: 60px !important;background-color: #f6f6f6 !important;}"][vc_column css=".vc_custom_1557549709978{background-color: #f6f6f6 !important;}"][vc_row_inner][vc_column_inner][vc_column_text animation="animation bottom-to-top" css=".vc_custom_1578965570523{margin-bottom: 0px !important;}"]
			<div style="text-align: center;">
			<h5 class="fancy-tag light-color">Flying Shoes</h5>
			</div>
			<h1 style="text-align: center;">Ultimate Running Shoes</h1>
			[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner et_column_align="align-center"][vc_column_inner animation="animation bottom-to-top" offset="vc_col-lg-9"][et_image_slider infinite="true" center="true" pagination="true" arrows="true" overflow="overflow-visible" autoplay="true" next_slides="overflow-visible" img_size="large" images="2106,2107,2108,2109"][vc_empty_space][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner animation="animation bottom-to-top"][vc_column_text css=".vc_custom_1573928305792{margin-bottom: 0px !important;}"]
			<div style="text-align: center;"></div>
			<p style="text-align: center;">Inspired by athletic tradition, reinvented for self-expression.</p>
			[/vc_column_text][vc_empty_space][et_button title="Design Your Own" add_arrow="true" size="lg" align="center" link="title:Bolt%20React%20Element%20Shoes||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1579113605824{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column][vc_row_inner et_column_align="align-center" content_placement="middle"][vc_column_inner animation="animation left-to-right" offset="vc_col-lg-4"][vc_column_text animation="animation bottom-to-top" css=".vc_custom_1573928146165{margin-bottom: 0px !important;}"]
			<h5 style="text-align: center;"><label class="fancy-tag">TOP SPEED</label></h5>
			<h1 style="text-align: center;">Your perfect running partner</h1>
			<p style="text-align: center;">Cushioned and lightweight running shoes for all distances.</p>
			[/vc_column_text][/vc_column_inner][vc_column_inner animation="animation right-to-left-3d" offset="vc_col-lg-6"][et_video_lightbox style="lightbox-image" icon_size="large" hover_style="hover-zoom" video="https://www.youtube.com/watch?v=ugLX59t3sqM" image="2108"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" css=".vc_custom_1579113590633{padding-top: 60px !important;background-color: #f6f6f6 !important;}"][vc_column][vc_row_inner et_column_align="align-center" content_placement="middle"][vc_column_inner animation="animation bottom-to-top" offset="vc_col-lg-6"][vc_column_text css=".vc_custom_1578437511907{margin-bottom: 0px !important;}"]
			<h1 style="text-align: center;">Running &amp; Streetwear</h1>
			<p style="text-align: center;">Running shoes that combine performance and style for the fashion-conscious runner.</p>
			[/vc_column_text][vc_empty_space][et_button title="Preorder Now" add_arrow="true" size="lg" align="center" link="title:Bolt%20React%20Element%20Shoes||"][vc_empty_space][/vc_column_inner][/vc_row_inner][vc_row_inner et_max_width="" et_column_align="align-center" content_placement="middle"][vc_column_inner offset="vc_col-lg-6"][et_image animation="animation bottom-to-top" alignment="aligncenter" image="3360"][/et_image][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_column_align="align-center" css=".vc_custom_1579113617984{padding-top: 60px !important;padding-bottom: 60px !important;}"][vc_column width="1/2" animation="animation bottom-to-top"][vc_tta_accordion active_section="1"][vc_tta_section title="Benefits" tab_id="1557543124640-60cb9bb3-2cc81e2a-fd4d"][vc_column_text]Sriracha la croix poutine, af try-hard readymade chambray pinterest vape glossier mlkshk you probably havent heard of them cray. Franzen 8-bit mixtape master cleanse swag trust fund.[/vc_column_text][/vc_tta_section][vc_tta_section title="Specifications" tab_id="1557543124710-e0287025-a0eb1e2a-fd4d"][vc_column_text]
			<ul>
			 	<li>Synthetic and textile upper</li>
			 	<li>Pull tab at the heel</li>
			 	<li>Shown: Black/Laser Fuchsia/White/Black</li>
			 	<li>Style: BQ9241-002</li>
			</ul>
			[/vc_column_text][/vc_tta_section][/vc_tta_accordion][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" css=".vc_custom_1579113623784{padding-top: 60px !important;background-color: #f6f6f6 !important;}"][vc_column][vc_row_inner et_column_align="align-center" content_placement="middle"][vc_column_inner animation="animation bottom-to-top" offset="vc_col-lg-6"][vc_column_text css=".vc_custom_1578432561206{padding-right: 10% !important;padding-left: 10% !important;}"]
			<h2 style="text-align: center;">An Element Of Surprise</h2>
			<p style="text-align: center;">A lightweight textile upper design takes its cue from iconic Nike sneakers like the Internationalist.</p>
			[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner et_max_width="" et_column_align="align-center" content_placement="middle"][vc_column_inner animation="animation right-to-left" offset="vc_col-lg-6"][et_image image="3356"][/et_image][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_column_align="align-center" css=".vc_custom_1579113636648{padding-top: 60px !important;padding-bottom: 40px !important;}"][vc_column width="1/2"][vc_column_text css=".vc_custom_1578432525100{padding-right: 10% !important;padding-left: 10% !important;}"]
			<h2 style="text-align: center;">Easy Rider</h2>
			<p style="text-align: center;">Nike React foam cushioning is a lightweight, durable design that is also ultra-soft and incredibly springy. With every step, the foam responds to your foot by snapping back.</p>
			[/vc_column_text][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" full_height="yes" css=".vc_custom_1580269974506{background-image: url(https://goyacdn.everthemes.com/demo-fashion/wp-content/uploads/sites/3/2020/01/react-extended2.jpg?id=3363) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][/vc_column][/vc_row][vc_row et_column_align="align-center" css=".vc_custom_1579113644722{padding-top: 60px !important;padding-bottom: 40px !important;}"][vc_column width="1/2"][vc_column_text css=".vc_custom_1578432534917{padding-right: 10% !important;padding-left: 10% !important;}"]
			<h2 style="text-align: center;">Durable Traction</h2>
			<p style="text-align: center;">The rubber pods on the midsole and outsole of the sneaker are more than an eye-catching design element. They make the shoe more durable and add traction.</p>
			[/vc_column_text][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center" full_height="yes" css=".vc_custom_1580269968945{background-image: url(https://goyacdn.everthemes.com/demo-fashion/wp-content/uploads/sites/3/2020/01/react-extended.jpg?id=3362) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner et_column_align="align-center"][vc_column_inner et_column_color="et-light-column" width="1/2"][vc_column_text]
			<h5 style="text-align: center;"><span class="fancy-tag accent-color">Shopping Options</span></h5>
			<h1 style="text-align: center;">Shoes React Element</h1>
			<p style="text-align: center;">Gluten-free trust fund poutine pug cloud</p>
			[/vc_column_text][et_button title="Find Locations" add_arrow="true" animation="animation bottom-to-top" color="light" shadow="button-shadow" align="center" link="||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	
	$template_list['home_10'] = array(
		'name' => esc_html__( 'Fashion 05 - Video Background', 'goya-core' ),
		'thumbnail' => GOYA_THEME_URI . "/assets/img/visual-composer/templates/homepages/home-h9.jpg",
		'cat' => array( 'homepage' ),
		'sc' => '[vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center" full_height="yes" content_placement="middle" video_bg="yes" video_bg_url="https://www.youtube.com/watch?v=ugLX59t3sqM"][vc_column][vc_row_inner et_column_align="align-center" content_placement="middle"][vc_column_inner et_column_color="et-light-column" width="1/2" animation="animation bottom-to-top"][et_typestroke slide_text="#E-8_JTNDaDIlMjBjbGFzcyUzRCUyMnRleHQtY2VudGVyJTIyJTNFJTNDc3Ryb25nJTNFVEhFJTIwU1VNTUVSJTIwTE9PSyUzQyUyRnN0cm9uZyUzRSUzQyUyRmgyJTNF" text_size="xxlarge" stroke_width="2px"][vc_column_text]
			<h4 style="text-align: center;">Make theyre Air to after stars night us winged Place</h4>
			[/vc_column_text][et_button title="Get the look" add_arrow="true" animation="animation bottom-to-top" color="light" shadow="button-shadow" align="center" link="||" text_color="#000000"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" et_column_align="align-center" content_placement="middle" css=".vc_custom_1579114326284{padding-top: 60px !important;padding-bottom: 60px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: contain !important;}"][vc_column][vc_row_inner et_column_align="align-center" content_placement="middle"][vc_column_inner width="1/2" animation="animation right-to-left"][et_image image="3814" img_size="large"][/et_image][/vc_column_inner][vc_column_inner et_column_overlap="overlap-left" width="1/3" animation="animation left-to-right"][vc_column_text]
			<h1>Get the look</h1>
			Make theyre Air to after stars night us winged Place for abundantly.[/vc_column_text][et_button title="Look Book" animation="animation bottom-to-top" link="title:Shop|target:%20_blank|"][vc_empty_space][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" content_placement="middle" css=".vc_custom_1579114442306{padding-bottom: 40px !important;}"][vc_column][vc_row_inner equal_height="yes" content_placement="middle" el_class="align-center"][vc_column_inner animation="animation bottom-to-top" offset="vc_col-lg-5" css=".vc_custom_1580059976362{margin-bottom: 30px !important;padding-top: 10% !important;padding-right: 10% !important;padding-bottom: 10% !important;padding-left: 10% !important;}"][vc_column_text]
			<h6 class="fancy-tag accent-color">Featured</h6>
			<h2>LookBook</h2>
			Pop-up mixtape pinterest succulents raclette everyday carry. Microdosing glossier drinking vinegar.[/vc_column_text][et_button title="All Looks" add_arrow="true" style="outlined" link="||"][/vc_column_inner][vc_column_inner animation="animation top-to-bottom" offset="vc_col-lg-7"][et_portfolio portfolio_layout="masonry" columns="col-12 col-lg-6" item_style="overlay" num_posts="4"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" content_placement="middle" css=".vc_custom_1578978537835{padding-top: 140px !important;padding-bottom: 140px !important;background-image: url(https://goyacdn.everthemes.com/demo-fashion/wp-content/uploads/sites/3/2020/01/boutique.jpg?id=3545) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner content_placement="middle"][vc_column_inner animation="animation bottom-to-top" css=".vc_custom_1578978517654{padding-top: 40px !important;padding-right: 40px !important;padding-bottom: 40px !important;padding-left: 40px !important;background-color: #ffffff !important;}" offset="vc_col-lg-4"][vc_column_text]
			<h2>Back to School</h2>
			Make theyre Air to after stars night us winged Place for man life deep.[/vc_column_text][et_button title="Look Book" link="title:Shop|target:%20_blank|" text_color="#000000"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" content_placement="middle" css=".vc_custom_1579114365520{padding-top: 60px !important;padding-bottom: 60px !important;background-position: center !important;background-repeat: no-repeat !important;background-size: contain !important;}"][vc_column][vc_row_inner][vc_column_inner][vc_column_text]
			<div class="wpb_text_column wpb_content_element ">
			<div class="wpb_wrapper">
			<h2 style="text-align: center;">Trending Outfits</h2>
			<p style="text-align: center;">Intelligentsia migas next level 90’s woke ramps. Glossier vape celiac tumeric keffiyeh.</p>

			</div>
			</div>
			[/vc_column_text][et_product_slider product_sort="latest-products" item_count="8" item_style="style4" show_variations="true"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row et_full_width="true" et_row_padding="true" content_placement="middle" css=".vc_custom_1578978546208{padding-top: 140px !important;padding-bottom: 140px !important;background-image: url(https://goyacdn.everthemes.com/demo-fashion/wp-content/uploads/sites/3/2019/04/student.jpg?id=1716) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner content_placement="middle"][vc_column_inner animation="animation bottom-to-top" css=".vc_custom_1578978561435{padding-top: 40px !important;padding-right: 40px !important;padding-bottom: 40px !important;padding-left: 40px !important;background-color: #ffffff !important;}" offset="vc_col-lg-4"][vc_column_text]
			<h2>Nightlife</h2>
			Make theyre Air to after stars night us winged Place for abundantly seas youre cattle.[/vc_column_text][et_button title="Look Book" link="title:Shop|target:%20_blank|" text_color="#000000"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);

	return $template_list;
}